### ISSUE TITLE
Patient_ValueSet_patient.speciesCode

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#33]
Submitter: Harsh Sharma
Organization: Alberta Health Services

Profile: Patient
Change Category: ValueSet
Element: patient.speciesCode

Rationale: Add species code to patient profile.

Feedback: Information about an individual or animal receiving health care services. The species of living organism. This may include the common or scientific name, based on the coding system(s) used.

**Comment by finnieflores** [comment]
There is an extension for species http://hl7.org/fhir/R4/extension-patient-animal.html. Similar to breed, I don't believe that species belong in CA baseline.

**Comment by kensinn** [comment]
Patient.animal.species and Patient.animal.breed were removed when evolving from FHIR STU3 to FHIR R4, due to lack of common "80% of implementations" usage.

https://www.hl7.org/fhir/patient.html#veterinary
"Veterinary care is very much within the scope of FHIR, and the Patient resource can be used to communicate information about animal patients. To support this, there is a standard patient-animal extension which can be used for recording details about species, breed, and gender status."

**Comment by russbuchanan** [comment]
The current description for the implementation guide says "basic interoperability expectations for **human-patient** systems in the Canadian space.

**Comment by sheridancook** [comment]
Hi @harshsharma09 , is this issue ok to close? Otherwise, we'll keep it open for discussion.

**Comment by harshsharma09** [comment]
@sheridancook yes please, we can close this issue. Is there a way to archive the comments?
