### ISSUE TITLE
Patient_ValueSet_patient.breedCode

### ISSUE THREAD

**Issue by Mike-JL-Savage** [scratch-fhir-profiles/CA-Core#34]
Submitter: Harsh Sharma
Organization: Alberta Health Services

Profile: Patient
Change Category: ValueSet
Element: patient.breedCode

Rationale: Add Breed code to patient profile.

Feedback: The specific breed of animal.

**Comment by finnieflores** [comment]
There is an extension for breed http://hl7.org/fhir/R4/extension-patient-animal.html. I don't believe that breed belongs to baseline CA.

**Comment by kensinn** [comment]
Patient.animal.species and Patient.animal.breed were removed when evolving from FHIR STU3 to FHIR R4, due to lack of common "80% of implementations" usage.

https://www.hl7.org/fhir/patient.html#veterinary
"Veterinary care is very much within the scope of FHIR, and the Patient resource can be used to communicate information about animal patients. To support this, there is a standard patient-animal extension which can be used for recording details about species, breed, and gender status."

**Comment by russbuchanan** [comment]
The current description for the implementation guide says "basic interoperability expectations for **human-patient** systems in the Canadian space.

**Comment by harshsharma09** [comment]
Hi Russ and Ken, Thanks for the comment. it makes sense.

**Comment by sheridancook** [comment]
Hi @harshsharma09 , is this issue still open or are we ok to close it based on the clarification above?

**Comment by harshsharma09** [comment]
@sheridancook yes please, we can close this issue. Is there a way to archive the comments? Thanks
