### ISSUE TITLE
Patient.language

### ISSUE THREAD

**Issue by michel-boivin** [scratch-fhir-profiles/CA-Core#36]
How does Patient.language relates to Patient.communication attribute ? 

Patient.language is defined as " The base language in which the resource is written", with cardinality 0..1, but this is very limitative. What if the patient is multi-language fluent (speaking/written)?

If the intend of Patient.language was to capture the first language learned from parents, it should be described as native language. This makes sense with cardinality 0..1,

Oherwise if the intend of Patient.language was to capture the prefered communication language, in this case it duplicates with Patient.communication data attribute and should be resolved. Specific rules should be defined accordingly.

**Comment by kensinn** [comment]
Patient.language is inherited from Resource.language (https://www.hl7.org/fhir/resource.html#resource), which tells you what language the content of the Resource is in. Whether the resource is Patient or Practitioner or Organization resource, the same description applies -- Patient.language or Practitioner.language or Organization.language tells you that everything in the resource will be in English or French or Italian, for example, so you should expect that the Narrative content, and Address lines, and other non-coded content will be in that language. 

Patient.communication.language is the communication language that the patient uses, which is why it's 0..*, in cases where the Patient can communicate in multiple languages, one (or many) of them can be marked as the patient's "preferred" language (using Patient.communication.language.preferred boolean).

**Comment by michel-boivin** [comment]
OK, I had concerns about mixed language documents and I did'nt catch that that the Patient.language attribute is used "to support indexing and accessibility". So there is no issue about this, knowing that "Not all the content has to be in the base language", as stated in the comments.
