### ISSUE TITLE
Practitioner_Slicing_identifier

### ISSUE THREAD

**Issue by kensinn** [scratch-fhir-profiles/CA-Core#50]
Reviewer: Ken Sinn
Organization: eHealth Ontario

Suggest that Practitioner.identifier be left unsliced. US-Core currently slices because of a national provider identifier, which Canada does not have. The level of granularity for slicing a Practitioner.identifier feels like overkill for a CA-Core specification.
In addition, distinction between identifier types are not immediately clear - what is the difference between a Provider Number (type=PRN) vs Licence Number (type=LN) vs Medical Doctor Number (type=MD)? Currently the Cdn FHIR URI registry lists all college identifiers as type PRN, even if some may be considered Licence Numbers. Suggest leaving this level of granularity/slicing to jurisdictions to provide additional specificity in their implementations.

**Comment by sbprior** [comment]
Hi- just some additional information- there is a system of national identifiers for physicians:
https://mcc.ca/examinations/minc/
The *Medical Identification Number for Canada* was, I believe, developed as part of an initiative to harmonize licensing requirements; I've never seen it used as such (maybe here?) 
I can think of use cases that would need different types of identifiers- e-prescribing (license info), provider number (billing for a referral), doctor number (attached to correspondence, may or may not be same as license- depends on College).
Oddly- because licensing of physicians (indeed most if not all regulated professionals) is provincial is this not a case to retain slicing into prn/ln/mdn?

**Comment by russbuchanan** [comment]
Discussion on 8/16/2019:
Right now there isn't much difference between the slices.
Meaning of PRN and LN are unclear.
May vary by Jurisdiction.
There is a distinction between a "billing number" vs a "license number" and the documentation should provide more information on when and how to use which.  (AB and BC examples were cited.)
Further research is needed to understand differences between regions if slicing is to be retained.  

Suggestion is to remove slicing until there is clear requirements for slicing identifiers on Practitioner.  Implement and allow folks to respond.

**Comment by russbuchanan** [comment]
Committed change to repository.
